name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        kind: ['linux'] #, 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          ##- kind: windows
          ##  os: windows-latest
          ##  target: win-x64
          ##- kind: macOS
          ##  os: macos-latest
          ##  target: osx-x64
    runs-on: ${{ matrix.os }} 
    
    defaults:
      run:
        working-directory: DemoRazorApp

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Create Env Vars
      shell: bash
      run: |
        # Define some variables for things we need
        tag=$(git describe --tags --abbrev=0)
        release_name="DemoRazorApp-$tag-${{ matrix.target }}" 
        echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV
        
 
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish --runtime "${{ matrix.target }}" -c Release -o "/${{ env.RELEASE_NAME }}"

    - name: Upload DemoRazorApp Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DemoRazorApp
        path: /${{ env.RELEASE_NAME }}

     
